package com.example.data.api

import android.util.Log
import com.example.BuildConfig
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Path
import retrofit2.http.Query
import retrofit2.http.Header
import retrofit2.http.Url
import java.util.concurrent.TimeUnit

interface GeminiService {
    @POST("v1beta/models/{model}:generateContent")
    suspend fun generateContent(
        @Path("model") model: String,
        @Query("key") apiKey: String,
        @Body request: GeminiRequest
    ): GeminiResponse
}

interface OpenAiService {
    @POST
    suspend fun generateContent(
        @Url url: String,
        @Header("Authorization") authHeader: String,
        @Body request: OpenAiRequest
    ): OpenAiResponse
}

object GeminiApiClient {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/"

    private val moshi = Moshi.Builder()
        .addLast(KotlinJsonAdapterFactory())
        .build()

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    private val retrofit = Retrofit.Builder()
        .baseUrl(BASE_URL)
        .client(okHttpClient)
        .addConverterFactory(MoshiConverterFactory.create(moshi))
        .build()

    val service: GeminiService = retrofit.create(GeminiService::class.java)
    val openAiService: OpenAiService = retrofit.create(OpenAiService::class.java)

    suspend fun generate(
        prompt: String,
        systemInstruction: String? = null,
        userApiKey: String? = null,
        modelOverride: String? = null,
        history: List<GeminiContent> = emptyList(),
        temperature: Float? = null,
        customOpenAiKey: String? = null,
        customOpenAiUrl: String? = null
    ): String {
        val resolvedModel = if (!modelOverride.isNullOrBlank()) {
            modelOverride
        } else {
            "gemini-3.5-flash"
        }

        // If custom OpenAI URL is enabled, route via OpenAI Chat Completions protocol
        if (!customOpenAiUrl.isNullOrBlank()) {
            return generateOpenAi(
                prompt = prompt,
                systemInstruction = systemInstruction,
                apiKey = customOpenAiKey ?: "",
                endpointUrl = customOpenAiUrl,
                model = resolvedModel,
                history = history,
                temperature = temperature ?: 1.0f
            )
        }

        // Fallback to BuildConfig key if user key is empty or null
        val key = if (userApiKey.isNullOrBlank()) {
            BuildConfig.GEMINI_API_KEY
        } else {
            userApiKey
        }

        // Combine history + latest user prompt
        val contents = history.toMutableList()
        contents.add(
            GeminiContent(
                role = "user",
                parts = listOf(GeminiPart(text = prompt))
            )
        )

        val req = GeminiRequest(
            contents = contents,
            generationConfig = GeminiGenerationConfig(
                temperature = temperature ?: 1.0f,
                maxOutputTokens = 2048
            ),
            systemInstruction = systemInstruction?.let {
                GeminiContent(parts = listOf(GeminiPart(text = it)))
            }
        )

        return try {
            val response = service.generateContent(resolvedModel, key, req)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                ?: "No response received. Check model/API configuration."
        } catch (e: Exception) {
            Log.e("GeminiApiClient", "Generation error", e)
            "Error generated by AI client: ${e.localizedMessage ?: e.message}"
        }
    }

    private suspend fun generateOpenAi(
        prompt: String,
        systemInstruction: String?,
        apiKey: String,
        endpointUrl: String,
        model: String,
        history: List<GeminiContent>,
        temperature: Float
    ): String {
        var targetUrl = endpointUrl.trim()
        if (!targetUrl.endsWith("/chat/completions") && !targetUrl.endsWith("/chat/completions/")) {
            if (targetUrl.endsWith("/")) {
                targetUrl += "chat/completions"
            } else {
                targetUrl += "/chat/completions"
            }
        }

        val messages = mutableListOf<OpenAiMessage>()
        if (!systemInstruction.isNullOrBlank()) {
            messages.add(OpenAiMessage(role = "system", content = systemInstruction))
        }

        for (h in history) {
            val role = when (h.role) {
                "user" -> "user"
                "model" -> "assistant"
                else -> "user"
            }
            val text = h.parts.firstOrNull()?.text ?: ""
            if (text.isNotBlank()) {
                messages.add(OpenAiMessage(role = role, content = text))
            }
        }

        messages.add(OpenAiMessage(role = "user", content = prompt))

        val req = OpenAiRequest(
            model = model,
            messages = messages,
            temperature = temperature,
            max_tokens = 2048
        )

        val authHeader = "Bearer $apiKey"

        return try {
            val response = openAiService.generateContent(targetUrl, authHeader, req)
            response.choices?.firstOrNull()?.message?.content
                ?: "No response received. Check OpenAI endpoint/API configuration."
        } catch (e: Exception) {
            Log.e("GeminiApiClient", "OpenAI Generation error on URL: $targetUrl", e)
            "Error generated by OpenAI custom client: ${e.localizedMessage ?: e.message}"
        }
    }
}
