package com.example.data.api

import android.util.Log
import com.example.BuildConfig
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Path
import retrofit2.http.Query
import java.util.concurrent.TimeUnit

interface GeminiService {
    @POST("v1beta/models/{model}:generateContent")
    suspend fun generateContent(
        @Path("model") model: String,
        @Query("key") apiKey: String,
        @Body request: GeminiRequest
    ): GeminiResponse
}

object GeminiApiClient {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/"

    private val moshi = Moshi.Builder()
        .addLast(KotlinJsonAdapterFactory())
        .build()

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    private val retrofit = Retrofit.Builder()
        .baseUrl(BASE_URL)
        .client(okHttpClient)
        .addConverterFactory(MoshiConverterFactory.create(moshi))
        .build()

    val service: GeminiService = retrofit.create(GeminiService::class.java)

    suspend fun generate(
        prompt: String,
        systemInstruction: String? = null,
        userApiKey: String? = null,
        modelOverride: String? = null,
        history: List<GeminiContent> = emptyList(),
        temperature: Float? = null
    ): String {
        // Fallback to BuildConfig key if user key is empty or null
        val key = if (userApiKey.isNullOrBlank()) {
            BuildConfig.GEMINI_API_KEY
        } else {
            userApiKey
        }

        val resolvedModel = if (!modelOverride.isNullOrBlank()) {
            modelOverride
        } else {
            "gemini-3.5-flash"
        }

        // Combine history + latest user prompt
        val contents = history.toMutableList()
        contents.add(
            GeminiContent(
                role = "user",
                parts = listOf(GeminiPart(text = prompt))
            )
        )

        val req = GeminiRequest(
            contents = contents,
            generationConfig = GeminiGenerationConfig(
                temperature = temperature ?: 1.0f,
                maxOutputTokens = 2048
            ),
            systemInstruction = systemInstruction?.let {
                GeminiContent(parts = listOf(GeminiPart(text = it)))
            }
        )

        return try {
            val response = service.generateContent(resolvedModel, key, req)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                ?: "No response received. Check model/API configuration."
        } catch (e: Exception) {
            Log.e("GeminiApiClient", "Generation error", e)
            "Error generated by AI client: ${e.localizedMessage ?: e.message}"
        }
    }
}
